version: '3.9'
services:
    app:
      container_name: payment_app  # Container name
      build: .
      volumes: 
        - '/usr/src/app' 
      ports: 
        - '4200:4200'
      command: > 
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"